version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.16
    - 1.18.18
  - dependency-name: org.json:json
    versions:
    - "20201115"
